# Generated by Django 6.0 on 2025-12-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('general-contracting', 'general-contracting'), ('design-build', 'design-build'), ('construction-management', 'construction-management'), ('pre-construction', 'pre-construction'), ('renovation', 'renovation'), ('specialty-services', 'specialty-services')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('general-contracting', 'general-contracting'), ('design-build', 'design-build'), ('construction-management', 'construction-management'), ('pre-construction', 'pre-construction'), ('renovation', 'renovation'), ('specialty-services', 'specialty-services')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
