# Generated by Django 6.0 on 2025-12-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial'), ('industrial', 'industrial'), ('infrastructure', 'infrastructure'), ('renovation', 'renovation'), ('other', 'other')], max_length=50)),
                ('budget', models.CharField(choices=[('under-10k', 'under-10k'), ('10k-50k', '10k-50k'), ('50k-100k', '50k-100k'), ('100k-500k', '100k-500k'), ('over-500k', 'over-500k'), ('discuss', 'discuss')], default='discuss', max_length=50)),
                ('timeline', models.CharField(choices=[('asap', 'asap'), ('1-3-months', '1-3-months'), ('3-6-months', '3-6-months'), ('6-12-months', '6-12-months'), ('over-1-year', 'over-1-year'), ('discuss', 'discuss')], default='discuss', max_length=50)),
                ('message', models.TextField(max_length=2000)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('preferred_contact', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'new'), ('in-review', 'in-review'), ('responded', 'responded'), ('closed', 'closed')], default='new', max_length=20)),
                ('source', models.CharField(default='website', max_length=50)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('admin_notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('project_type', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial'), ('industrial', 'industrial'), ('infrastructure', 'infrastructure'), ('renovation', 'renovation'), ('other', 'other')], max_length=50)),
                ('budget', models.CharField(choices=[('under-10k', 'under-10k'), ('10k-50k', '10k-50k'), ('50k-100k', '50k-100k'), ('100k-500k', '100k-500k'), ('over-500k', 'over-500k'), ('discuss', 'discuss')], default='discuss', max_length=50)),
                ('timeline', models.CharField(choices=[('asap', 'asap'), ('1-3-months', '1-3-months'), ('3-6-months', '3-6-months'), ('6-12-months', '6-12-months'), ('over-1-year', 'over-1-year'), ('discuss', 'discuss')], default='discuss', max_length=50)),
                ('message', models.TextField(max_length=2000)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('preferred_contact', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'new'), ('in-review', 'in-review'), ('responded', 'responded'), ('closed', 'closed')], default='new', max_length=20)),
                ('source', models.CharField(default='website', max_length=50)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
