# Generated by Django 6.0 on 2025-12-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('long_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('employees', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('500+', '500+')], max_length=50, null=True)),
                ('headquarters', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('licenses', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('awards', models.JSONField(blank=True, default=list)),
                ('values', models.JSONField(blank=True, default=list)),
                ('mission', models.TextField(blank=True, max_length=500, null=True)),
                ('vision', models.TextField(blank=True, max_length=500, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=255, null=True)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
